# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\LZC-solo\Desktop\qt_view\Robot_sim.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 353)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_4 = QtWidgets.QWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.slide_1 = QtWidgets.QSlider(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.slide_1.setFont(font)
        self.slide_1.setMinimum(-1800)
        self.slide_1.setMaximum(1800)
        self.slide_1.setPageStep(1)
        self.slide_1.setOrientation(QtCore.Qt.Horizontal)
        self.slide_1.setObjectName("slide_1")
        self.horizontalLayout.addWidget(self.slide_1)
        self.slide_v_9 = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.slide_v_9.setDecimals(1)
        self.slide_v_9.setMinimum(-135.0)
        self.slide_v_9.setMaximum(135.0)
        self.slide_v_9.setObjectName("slide_v_9")
        self.horizontalLayout.addWidget(self.slide_v_9)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.slide_2 = QtWidgets.QSlider(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.slide_2.setFont(font)
        self.slide_2.setMinimum(-1350)
        self.slide_2.setMaximum(1350)
        self.slide_2.setOrientation(QtCore.Qt.Horizontal)
        self.slide_2.setObjectName("slide_2")
        self.horizontalLayout_2.addWidget(self.slide_2)
        self.slide_v_8 = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.slide_v_8.setDecimals(1)
        self.slide_v_8.setMinimum(-135.0)
        self.slide_v_8.setMaximum(135.0)
        self.slide_v_8.setObjectName("slide_v_8")
        self.horizontalLayout_2.addWidget(self.slide_v_8)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_5.setFont(font)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.slide_3 = QtWidgets.QSlider(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.slide_3.setFont(font)
        self.slide_3.setMinimum(-1350)
        self.slide_3.setMaximum(1350)
        self.slide_3.setOrientation(QtCore.Qt.Horizontal)
        self.slide_3.setObjectName("slide_3")
        self.horizontalLayout_3.addWidget(self.slide_3)
        self.slide_v_7 = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.slide_v_7.setDecimals(1)
        self.slide_v_7.setMinimum(-135.0)
        self.slide_v_7.setMaximum(135.0)
        self.slide_v_7.setObjectName("slide_v_7")
        self.horizontalLayout_3.addWidget(self.slide_v_7)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_6.setFont(font)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.slide_4 = QtWidgets.QSlider(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.slide_4.setFont(font)
        self.slide_4.setMinimum(-1350)
        self.slide_4.setMaximum(1350)
        self.slide_4.setOrientation(QtCore.Qt.Horizontal)
        self.slide_4.setObjectName("slide_4")
        self.horizontalLayout_4.addWidget(self.slide_4)
        self.slide_v_6 = QtWidgets.QDoubleSpinBox(self.widget_6)
        self.slide_v_6.setDecimals(1)
        self.slide_v_6.setMinimum(-135.0)
        self.slide_v_6.setMaximum(135.0)
        self.slide_v_6.setObjectName("slide_v_6")
        self.horizontalLayout_4.addWidget(self.slide_v_6)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget = QtWidgets.QWidget(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.slide_5 = QtWidgets.QSlider(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.slide_5.setFont(font)
        self.slide_5.setMinimum(-1350)
        self.slide_5.setMaximum(1350)
        self.slide_5.setSingleStep(0)
        self.slide_5.setPageStep(0)
        self.slide_5.setOrientation(QtCore.Qt.Horizontal)
        self.slide_5.setObjectName("slide_5")
        self.horizontalLayout_5.addWidget(self.slide_5)
        self.slide_v_5 = QtWidgets.QDoubleSpinBox(self.widget)
        self.slide_v_5.setDecimals(1)
        self.slide_v_5.setMinimum(-135.0)
        self.slide_v_5.setMaximum(135.0)
        self.slide_v_5.setObjectName("slide_v_5")
        self.horizontalLayout_5.addWidget(self.slide_v_5)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.widget_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "调节关节角度"))
        self.label_2.setText(_translate("Form", "关节一角度："))
        self.label_3.setText(_translate("Form", "关节二角度："))
        self.label_4.setText(_translate("Form", "关节三角度："))
        self.label_5.setText(_translate("Form", "关节四角度："))
        self.label_6.setText(_translate("Form", "关节五角度："))
