# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\LZC-solo\Desktop\qt_view\Robot_ui_files\robot_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Robot_form(object):
    def setupUi(self, Robot_form):
        Robot_form.setObjectName("Robot_form")
        Robot_form.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        Robot_form.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(Robot_form)
        self.centralwidget.setObjectName("centralwidget")
        self.img_sheet_big = QtWidgets.QLabel(self.centralwidget)
        self.img_sheet_big.setGeometry(QtCore.QRect(10, 100, 481, 421))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.img_sheet_big.setFont(font)
        self.img_sheet_big.setFrameShadow(QtWidgets.QFrame.Plain)
        self.img_sheet_big.setLineWidth(1)
        self.img_sheet_big.setObjectName("img_sheet_big")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(480, 240, 301, 311))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_5.setFont(font)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Slider_par1 = QtWidgets.QSlider(self.widget_5)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Slider_par1.setFont(font)
        self.Slider_par1.setMinimum(-180)
        self.Slider_par1.setMaximum(180)
        self.Slider_par1.setSliderPosition(0)
        self.Slider_par1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_par1.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Slider_par1.setObjectName("Slider_par1")
        self.horizontalLayout_2.addWidget(self.Slider_par1)
        self.par1 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.par1.sizePolicy().hasHeightForWidth())
        self.par1.setSizePolicy(sizePolicy)
        self.par1.setMinimumSize(QtCore.QSize(25, 0))
        self.par1.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.par1.setFont(font)
        self.par1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par1.setObjectName("par1")
        self.horizontalLayout_2.addWidget(self.par1)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_6.setFont(font)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Slider_par2 = QtWidgets.QSlider(self.widget_6)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Slider_par2.setFont(font)
        self.Slider_par2.setMinimum(-180)
        self.Slider_par2.setMaximum(180)
        self.Slider_par2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_par2.setObjectName("Slider_par2")
        self.horizontalLayout_3.addWidget(self.Slider_par2)
        self.par2 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.par2.sizePolicy().hasHeightForWidth())
        self.par2.setSizePolicy(sizePolicy)
        self.par2.setMinimumSize(QtCore.QSize(25, 0))
        self.par2.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.par2.setFont(font)
        self.par2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par2.setObjectName("par2")
        self.horizontalLayout_3.addWidget(self.par2)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_7.setFont(font)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.Slider_par3 = QtWidgets.QSlider(self.widget_7)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Slider_par3.setFont(font)
        self.Slider_par3.setMinimum(-180)
        self.Slider_par3.setMaximum(180)
        self.Slider_par3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_par3.setObjectName("Slider_par3")
        self.horizontalLayout_4.addWidget(self.Slider_par3)
        self.par3 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.par3.sizePolicy().hasHeightForWidth())
        self.par3.setSizePolicy(sizePolicy)
        self.par3.setMinimumSize(QtCore.QSize(25, 0))
        self.par3.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.par3.setFont(font)
        self.par3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par3.setObjectName("par3")
        self.horizontalLayout_4.addWidget(self.par3)
        self.verticalLayout.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_8.setFont(font)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.Slider_par4 = QtWidgets.QSlider(self.widget_8)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Slider_par4.setFont(font)
        self.Slider_par4.setMinimum(-180)
        self.Slider_par4.setMaximum(180)
        self.Slider_par4.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_par4.setObjectName("Slider_par4")
        self.horizontalLayout_5.addWidget(self.Slider_par4)
        self.par4 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.par4.sizePolicy().hasHeightForWidth())
        self.par4.setSizePolicy(sizePolicy)
        self.par4.setMinimumSize(QtCore.QSize(25, 0))
        self.par4.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.par4.setFont(font)
        self.par4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par4.setObjectName("par4")
        self.horizontalLayout_5.addWidget(self.par4)
        self.verticalLayout.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_9.setFont(font)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.Slider_par5 = QtWidgets.QSlider(self.widget_9)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Slider_par5.setFont(font)
        self.Slider_par5.setMinimum(-180)
        self.Slider_par5.setMaximum(180)
        self.Slider_par5.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_par5.setObjectName("Slider_par5")
        self.horizontalLayout_6.addWidget(self.Slider_par5)
        self.par5 = QtWidgets.QLabel(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.par5.sizePolicy().hasHeightForWidth())
        self.par5.setSizePolicy(sizePolicy)
        self.par5.setMinimumSize(QtCore.QSize(25, 0))
        self.par5.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.par5.setFont(font)
        self.par5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par5.setObjectName("par5")
        self.horizontalLayout_6.addWidget(self.par5)
        self.verticalLayout.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_3)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget_10.setFont(font)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.Slider_par6 = QtWidgets.QSlider(self.widget_10)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Slider_par6.setFont(font)
        self.Slider_par6.setMinimum(-180)
        self.Slider_par6.setMaximum(180)
        self.Slider_par6.setSliderPosition(0)
        self.Slider_par6.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_par6.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Slider_par6.setObjectName("Slider_par6")
        self.horizontalLayout_7.addWidget(self.Slider_par6)
        self.par6 = QtWidgets.QLabel(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.par6.sizePolicy().hasHeightForWidth())
        self.par6.setSizePolicy(sizePolicy)
        self.par6.setMinimumSize(QtCore.QSize(25, 0))
        self.par6.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.par6.setFont(font)
        self.par6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par6.setObjectName("par6")
        self.horizontalLayout_7.addWidget(self.par6)
        self.verticalLayout.addWidget(self.widget_10)
        self.img_sheet_small = QtWidgets.QLabel(self.centralwidget)
        self.img_sheet_small.setGeometry(QtCore.QRect(580, 40, 141, 141))
        self.img_sheet_small.setObjectName("img_sheet_small")
        Robot_form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Robot_form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        Robot_form.setMenuBar(self.menubar)

        self.retranslateUi(Robot_form)
        QtCore.QMetaObject.connectSlotsByName(Robot_form)

    def retranslateUi(self, Robot_form):
        _translate = QtCore.QCoreApplication.translate
        Robot_form.setWindowTitle(_translate("Robot_form", "机器人操作平台"))
        self.img_sheet_big.setText(_translate("Robot_form", "TextLabel"))
        self.label_2.setText(_translate("Robot_form", "关节一："))
        self.par1.setText(_translate("Robot_form", "0"))
        self.label_3.setText(_translate("Robot_form", "关节二："))
        self.par2.setText(_translate("Robot_form", "0"))
        self.label_10.setText(_translate("Robot_form", "关节三："))
        self.par3.setText(_translate("Robot_form", "0"))
        self.label_7.setText(_translate("Robot_form", "关节四："))
        self.par4.setText(_translate("Robot_form", "0"))
        self.label_8.setText(_translate("Robot_form", "关节五："))
        self.par5.setText(_translate("Robot_form", "0"))
        self.label_4.setText(_translate("Robot_form", "关节六："))
        self.par6.setText(_translate("Robot_form", "0"))
        self.img_sheet_small.setText(_translate("Robot_form", "TextLabel"))
