# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\LZC-solo\Desktop\robot\Robot_ui_files\robot_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Robot_form(object):
    def setupUi(self, Robot_form):
        Robot_form.setObjectName("Robot_form")
        Robot_form.resize(879, 546)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Robot_form.sizePolicy().hasHeightForWidth())
        Robot_form.setSizePolicy(sizePolicy)
        Robot_form.setMinimumSize(QtCore.QSize(879, 546))
        Robot_form.setMaximumSize(QtCore.QSize(879, 546))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        Robot_form.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(Robot_form)
        self.centralwidget.setObjectName("centralwidget")
        self.img_sheet_big = QtWidgets.QLabel(self.centralwidget)
        self.img_sheet_big.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.img_sheet_big.setMinimumSize(QtCore.QSize(640, 480))
        self.img_sheet_big.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.img_sheet_big.setFont(font)
        self.img_sheet_big.setFrameShadow(QtWidgets.QFrame.Plain)
        self.img_sheet_big.setLineWidth(1)
        self.img_sheet_big.setAlignment(QtCore.Qt.AlignCenter)
        self.img_sheet_big.setObjectName("img_sheet_big")
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setGeometry(QtCore.QRect(680, 20, 191, 476))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.widget_8)
        self.widget_4.setMinimumSize(QtCore.QSize(170, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.state_ico = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.state_ico.setFont(font)
        self.state_ico.setText("")
        self.state_ico.setObjectName("state_ico")
        self.horizontalLayout_2.addWidget(self.state_ico)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.COM_edit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.COM_edit.setFont(font)
        self.COM_edit.setText("")
        self.COM_edit.setObjectName("COM_edit")
        self.horizontalLayout.addWidget(self.COM_edit)
        self.conn_butt = QtWidgets.QPushButton(self.widget)
        self.conn_butt.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.conn_butt.setFont(font)
        self.conn_butt.setObjectName("conn_butt")
        self.horizontalLayout.addWidget(self.conn_butt)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.verticalLayout_7.addWidget(self.widget_4)
        self.widget_10 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(170, 0))
        self.widget_10.setMaximumSize(QtCore.QSize(170, 16777215))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.offline_rad = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.offline_rad.setFont(font)
        self.offline_rad.setChecked(True)
        self.offline_rad.setObjectName("offline_rad")
        self.verticalLayout_2.addWidget(self.offline_rad)
        self.online_rad = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.online_rad.setFont(font)
        self.online_rad.setObjectName("online_rad")
        self.verticalLayout_2.addWidget(self.online_rad)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.verticalLayout_7.addWidget(self.widget_10)
        self.widget_9 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(170, 0))
        self.widget_9.setMaximumSize(QtCore.QSize(170, 16777215))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_8.setContentsMargins(11, 0, 11, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cap_state_butt = QtWidgets.QPushButton(self.widget_9)
        self.cap_state_butt.setMinimumSize(QtCore.QSize(150, 30))
        self.cap_state_butt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.cap_state_butt.setFont(font)
        self.cap_state_butt.setObjectName("cap_state_butt")
        self.verticalLayout_8.addWidget(self.cap_state_butt)
        self.verticalLayout_7.addWidget(self.widget_9)
        self.widget_7 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(170, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(170, 16777215))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.widget_5 = QtWidgets.QWidget(self.widget_7)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.par_butt = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.par_butt.sizePolicy().hasHeightForWidth())
        self.par_butt.setSizePolicy(sizePolicy)
        self.par_butt.setMinimumSize(QtCore.QSize(150, 30))
        self.par_butt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.par_butt.setFont(font)
        self.par_butt.setObjectName("par_butt")
        self.verticalLayout_4.addWidget(self.par_butt)
        self.car_butt = QtWidgets.QPushButton(self.widget_5)
        self.car_butt.setMinimumSize(QtCore.QSize(150, 30))
        self.car_butt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.car_butt.setFont(font)
        self.car_butt.setObjectName("car_butt")
        self.verticalLayout_4.addWidget(self.car_butt)
        self.guiji_butt = QtWidgets.QPushButton(self.widget_5)
        self.guiji_butt.setMinimumSize(QtCore.QSize(150, 30))
        self.guiji_butt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.guiji_butt.setFont(font)
        self.guiji_butt.setObjectName("guiji_butt")
        self.verticalLayout_4.addWidget(self.guiji_butt)
        self.widget_11 = QtWidgets.QWidget(self.widget_5)
        self.widget_11.setMinimumSize(QtCore.QSize(150, 30))
        self.widget_11.setMaximumSize(QtCore.QSize(150, 30))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reset_butt = QtWidgets.QPushButton(self.widget_11)
        self.reset_butt.setMinimumSize(QtCore.QSize(65, 30))
        self.reset_butt.setMaximumSize(QtCore.QSize(65, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.reset_butt.setFont(font)
        self.reset_butt.setObjectName("reset_butt")
        self.horizontalLayout_3.addWidget(self.reset_butt)
        self.hook_butt = QtWidgets.QPushButton(self.widget_11)
        self.hook_butt.setMinimumSize(QtCore.QSize(65, 30))
        self.hook_butt.setMaximumSize(QtCore.QSize(65, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.hook_butt.setFont(font)
        self.hook_butt.setObjectName("hook_butt")
        self.horizontalLayout_3.addWidget(self.hook_butt)
        self.verticalLayout_4.addWidget(self.widget_11)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.widget_6 = QtWidgets.QWidget(self.widget_7)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fun_butt = QtWidgets.QPushButton(self.widget_6)
        self.fun_butt.setMinimumSize(QtCore.QSize(150, 30))
        self.fun_butt.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.fun_butt.setFont(font)
        self.fun_butt.setObjectName("fun_butt")
        self.verticalLayout_5.addWidget(self.fun_butt)
        self.verticalLayout_6.addWidget(self.widget_6)
        self.verticalLayout_7.addWidget(self.widget_7)
        Robot_form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Robot_form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 25))
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        Robot_form.setMenuBar(self.menubar)
        self.actionpar_run = QtWidgets.QAction(Robot_form)
        self.actionpar_run.setObjectName("actionpar_run")
        self.actionCar_run = QtWidgets.QAction(Robot_form)
        self.actionCar_run.setObjectName("actionCar_run")
        self.actionhelp = QtWidgets.QAction(Robot_form)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout_us = QtWidgets.QAction(Robot_form)
        self.actionabout_us.setObjectName("actionabout_us")
        self.actionversion = QtWidgets.QAction(Robot_form)
        self.actionversion.setObjectName("actionversion")
        self.actionpath_arrange = QtWidgets.QAction(Robot_form)
        self.actionpath_arrange.setObjectName("actionpath_arrange")
        self.menu_2.addAction(self.actionhelp)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionabout_us)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionversion)
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Robot_form)
        QtCore.QMetaObject.connectSlotsByName(Robot_form)

    def retranslateUi(self, Robot_form):
        _translate = QtCore.QCoreApplication.translate
        Robot_form.setWindowTitle(_translate("Robot_form", "机器人操作平台"))
        self.img_sheet_big.setText(_translate("Robot_form", "TextLabel"))
        self.label.setText(_translate("Robot_form", "当前状态："))
        self.COM_edit.setPlaceholderText(_translate("Robot_form", "串口号"))
        self.conn_butt.setText(_translate("Robot_form", "连接"))
        self.conn_butt.setShortcut(_translate("Robot_form", "Return"))
        self.groupBox.setTitle(_translate("Robot_form", "调试模式"))
        self.offline_rad.setText(_translate("Robot_form", "离线仿真"))
        self.online_rad.setText(_translate("Robot_form", "本机调试"))
        self.cap_state_butt.setText(_translate("Robot_form", "开启摄像头"))
        self.label_2.setText(_translate("Robot_form", "基本功能："))
        self.par_butt.setText(_translate("Robot_form", "关节空间示教器"))
        self.car_butt.setText(_translate("Robot_form", "笛卡尔空间示教器"))
        self.guiji_butt.setText(_translate("Robot_form", "轨迹规划"))
        self.reset_butt.setText(_translate("Robot_form", "复位"))
        self.hook_butt.setText(_translate("Robot_form", "夹取"))
        self.label_3.setText(_translate("Robot_form", "人机交互："))
        self.fun_butt.setText(_translate("Robot_form", "娱乐模式"))
        self.menu_2.setTitle(_translate("Robot_form", "更多"))
        self.actionpar_run.setText(_translate("Robot_form", "关节空间示教器"))
        self.actionCar_run.setText(_translate("Robot_form", "笛卡尔空间示教器"))
        self.actionhelp.setText(_translate("Robot_form", "帮助"))
        self.actionabout_us.setText(_translate("Robot_form", "关于我们"))
        self.actionversion.setText(_translate("Robot_form", "版本"))
        self.actionpath_arrange.setText(_translate("Robot_form", "轨迹规划"))
